version: "3.8"

services:
  web:
    build: .
    command: gunicorn config.wsgi.application --bind 0.0.0.0:8005
    volumes:
      - ./static:/home/user/web/static/
      - ./media:/home/user/web/media/
    ports:
      - 8005:8005
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - selenium
      - redis

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  celery:
    build: .
    volumes:
      - .:/home/user/web/
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
      - web
    command: celery --app config worker --loglevel=debug --without-mingle --without-gossip

  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444

volumes:
  postgres_data:
  static_data:
  media_data:
